# Generated by Django 6.0.2 on 2026-02-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='priority',
            field=models.CharField(choices=[('HG', 'High'), ('MD', 'Medium'), ('LW', 'Low')], default='MD', max_length=15),
        ),
    ]
